### ISSUE TITLE
Hot reload of defined contracts

### ISSUE THREAD

**Issue by agraebe** [hirosystems/clarity-repl#15]
If a contract file changes, the console could hot reload the contract

**Comment by moodmosaic** [comment]
I'm don't think we should hot reload as it can be slow when there are a lot of contracts loaded in the session.

What has been working extremely well in battle-hardened REPLs (e.g. [GHCi](https://downloads.haskell.org/~ghc/8.6.5/docs/html/users_guide/ghci.html?highlight=reload#ghci-cmd-:reload)) is to explicitly reload, for example, ``::reload`` which would reload the contract(s) in the session.

**Comment by moodmosaic** [comment]
@obycode, @lgalabru, this might be a naïve question: how do I load a contract into clarity-repl? All I see is these commands:

```
>> ::help
::help                                  Display help
::list_functions                        Display all the native functions available in clarity
::describe_function <function>          Display documentation for a given native function fn-name
::mint_stx <principal> <amount>         Mint STX balance for a given principal
::set_tx_sender <principal>             Set tx-sender variable to principal
::get_assets_maps                       Get assets maps for active accounts
::get_costs <expr>                      Display the cost analysis
::get_contracts                         Get contracts
::get_block_height                      Get current block height
::advance_chain_tip <count>             Simulate mining of <count> blocks
::toggle_costs                          Display cost analysis after every expression
::debug <expr>                          Start an interactive debug session executing <expr>
``` 

My ignorance is mostly because up to know I've been using clarity-repl through `clarity console`. However, to add support for `::reload` I need to run load some contracts explicitly.

**Comment by obycode** [comment]
Thanks for investigating this. There isn't a command to load a contract currently. You would copy and paste it in. I'd recommend taking a look at the [code in clarinet](https://github.com/hirosystems/clarinet/blob/7e57cd2e0202b90a0d49b006c6407f815b4c24c9/src/frontend/cli.rs#L443-L485) that handles the `console` command.

**Comment by moodmosaic** [comment]
Hmm... Thanks. I'm not sure how we'll actually test the reload this way though. 🤔

**Comment by moodmosaic** [comment]
> I'd recommend taking a look at the [code in clarinet](https://github.com/hirosystems/clarinet/blob/7e57cd2e0202b90a0d49b006c6407f815b4c24c9/src/frontend/cli.rs#L443-L485) that handles the `console` command.

Thank you, @obycode. Is it correct to assume that, at high level, `::reload` would simply call [`load_session`](https://github.com/hirosystems/clarinet/blob/7e57cd2e0202b90a0d49b006c6407f815b4c24c9/src/poke/mod.rs#L108)?

**Comment by obycode** [comment]
Yes, I think that's probably correct, but I haven't gone through to see if there are any minor issues that will pop up or other items that need to be taken care of as well.

**Comment by moodmosaic** [comment]
Perhaps the easiest is to just rereate the Session?
