### ISSUE TITLE
ast_dependency_detector crashing

### ISSUE THREAD

**Issue by Oyeins-GUI** [hirosystems/clarity-repl#189]
thread 'main' panicked at 'called Result::unwrap() on an Err value: InvalidTypeDescription', C:\Users\runneradmin.cargo\registry\src\github.com-1ecc6299db9ec823\clarity-repl-0.27.0\src\analysis\ast_dependency_detector.rs:497:82
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

When I run the "clarinet check" command on the terminal I had this error above. How can I fix it?

**Comment by lgalabru** [comment]
I believe this issue was resolved by using clarinet latest update. @Oyeins-GUI I'll let you re-open it if this is not the case.

**Comment by Oyeins-GUI** [comment]
Thanks. The latest update fixed the issue
