### ISSUE TITLE
Industrialize clarity-repl.wasm builds and deployments

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarity-repl#28]
The current process for building `clarity-repl.wasm` is very manual and artisanal. The approach should be revisited and automated.

**Comment by lgalabru** [comment]
Additionally, new versions of the clarity-repl should be published on crates.io (https://crates.io/crates/clarity-repl)

**Comment by lgalabru** [comment]
Additionally, update https://hirosystems.github.io/clarity-repl/

**Comment by CharlieC3** [comment]
@lgalabru Does the clarity-repl need to be built on multiple distros like Clarinet? Or is it strictly going to be a cargo crate?

**Comment by lgalabru** [comment]
It's just the cargo crate, and the wasm build.
