### ISSUE TITLE
Wrong link in website

### ISSUE THREAD

**Issue by pinkpanthero** [hirosystems/clarity-repl#37]
In https://clarity-lang.org/d#started Clarity Playground hyperlinks to https://lgalabru.github.io/clarity-repl But the link does not work. The correct link is https://hirosystems.github.io/clarity-repl

**Comment by lgalabru** [comment]
@MarvinJanssen I think that this website is maintained by the Stacks foundation, is this something you could look into?

**Comment by obycode** [comment]
This bad link is still there. @criadoperez Are you able to fix this? Note the problem is only on dark-mode. Light mode links to a different playground.

**Comment by obycode** [comment]
I just followed the link from this issue (which is old), but once I was there, I believe I saw light/dark options at the bottom. Did they just get removed?

**Comment by cuevasm** [comment]
No, they've been gone at least a month or more, we retired that when we added the Clarity Universe page
