### ISSUE TITLE
Compatibility with Debug Adapter Protocol

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarity-repl#53]
What would it take to make the VM compatible with https://microsoft.github.io/debug-adapter-protocol/ ?

**Comment by lgalabru** [comment]
https://gist.github.com/fariedt/24dcef09824e061e5564833505a4d162

**Comment by fariedt** [comment]
an messy update: https://gist.github.com/fariedt/1f2cd4fe9a09e9823fa1d4d8513ed0dd

**Comment by obycode** [comment]
Latest updates:
* CLI debugger is released! https://github.com/hirosystems/debugger-demo
* DAP debugger in progress

Plan:
- [x] Create module to define DAP types - https://github.com/hirosystems/dap-types
- [x] Create a trait, `EvalHook`, with `begin_eval` and `finish_eval` methods
- [ ] Convert CLI debugger to use this new trait
- [ ] Convert coverage tracker to use this new trait
- [ ] Store a vector of these hooks in `GlobalContext`
- [ ] Update `clarity::eval` to cycle through this vector
- [ ] Extract common debugger functionality into a separate submodule to be used by both the CLI and DAP debuggers
- [ ] Create a DAP object that implements `EvalHook` for the DAP debugger

**Comment by obycode** [comment]
This is completed and released in 0.27.0 (and will be integrated into clarinet v0.30.0 as well).
