### ISSUE TITLE
Add .encode .decode commands

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarity-repl#7]
I'd like to be able to quickly encode and decode clarity values, based on the wire format from Stacks 2.0

**Comment by obycode** [comment]
Any preferred formatting for the encoded bytes?

For example:
```
00000000  57 69 6b 69 70 65 64 69  61 2c 20 74 68 65 20 66  
00000010  72 65 65 20 65 6e 63 79  63 6c 6f 70 65 64 69 61  
00000020  20 74 68 61 74 20 61 6e  79 6f 6e 65 20 63 61 6e 
00000030  20 65 64 69 74 0a
```

Or
```
57696b6970656469  612c207468652066  72656520656e6379  636c6f7065646961
207468617420616e  796f6e652063616e  20656469740a
```

**Comment by lgalabru** [comment]
This feature will probably be used in conjunction with the stacks-node RPC endpoints that let developers reading the chainstate. If I remember correctly, we use following the representation `0x094249300..43920`

**Comment by obycode** [comment]
Ok, so it is just one long string of hex digits?

**Comment by lgalabru** [comment]
Correct
