### ISSUE TITLE
Check-checker fine tuning: ability to detect untainting statements, post usage  

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarity-repl#81]
Another source of false positive. Not sure if this kind of cases should and can be addressed without introducing a nest of bugs. 

```
(define-map authorized-tokens
  { token: principal }
  { enabled: bool }
)

(define-read-only (get-token-acl (token principal))
  (default-to
    { enabled: false }
    (map-get? reserve-tokens { token: token })))

(define-public (do-something (token-trait <ft-trait>))
  (let (
    (token-balance (unwrap-panic (contract-call? token-trait get-balance (as-contract tx-sender))))
    (acl (get-token-acl (contract-of token-trait)))
  )
    (asserts! (get enabled acl) (err u0))
    ;; ...
    (ok u0)))

```

The generalization is unclear to me at the moment.
What do you think @obycode ?

**Comment by obycode** [comment]
This example is a bit unclear to me. Can you explain a bit more about what might qualify as a proper check on token-trait?

Based on the title of this bug though, you make a good point that a case like below should be fixed. This is based on the fact that:
> If a function returns an (err ...) type, and mutations on the blockchain state from executing the function (and any function that it called during execution) will be aborted.

```clarity
(define-public (filtered (amount uint))
    (begin
        (try! (stx-transfer? amount (as-contract tx-sender) tx-sender))
        (asserts! (< amount u100) (err u100))
        (ok true)
    )
)
```

**Comment by obycode** [comment]
This case is handled as of 0.25.0.
