### ISSUE TITLE
Improve support of get-block-info

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarity-repl#9]
Currently supported: `vrf-seed`, `time`, ` id-header-hash`, `miner-address`
Not supported: `burnchain-header-hash`, `header-hash`

EDIT
Currently supported: `vrf-seed`, `time`, ` id-header-hash`, `miner-address`, `burnchain-header-hash`
Not supported: `header-hash`

**Comment by lgalabru** [comment]
`burnchain-header-hash` is now supported.
I just tried `clarinet console` with clarinet 0.7.1 in https://github.com/friedger/clarity-friedger-pool/ - works as expected
cc @friedger

**Comment by LNow** [comment]
Would it be possible to add an additional function that would allow us to manually set value that `burnchain-header-hash` should return at specific block height?

Something like:
```
set_burnchain_header_hash(block_id, desired_value)
``` 
Then when the time comes to return value, return user defined value and if it has not been set calculate it using `StacksBlockId`.

It could be then exposed in `clarinet` and that two things combined together would make testing code like [this one](https://github.com/jcnelson/clarity-bitcoin/blob/8b7079cea4c09114f9049191cc8fa96f49c9254d/clarity-bitcoin.clar#L641-L646) not only possible, but very easy.

**Comment by obycode** [comment]
Addressed in latest clarity-repl.
